force-app/main/default/objects/Lead/fields/Estimated_Deal_Value_c__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Deal_Value_c__c</fullName>
    <label>Estimated_Deal_Value_c</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Marketing_Consent_c__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Consent_c__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketing_Consent_c</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory_Assignment_Rule__mdt/Territory_Assignment_Rule__mdt.object-meta.xml
<CustomObject>
    <label>Territory Assignment Rule</label>
    <pluralLabel>Territory Assignment Rules</pluralLabel>
</CustomObject>

force-app/main/default/classes/LeadTriggerHandler.cls
public class LeadTriggerHandler {

    public static void handleBeforeInsert(List<Lead> newLeads) {

        // 1. Calculate Lead Score
        for (Lead lead : newLeads) {

            Integer score = 0;

            if (lead.Marketing_Consent_c__c == true) {
                score += 30;
            }

            if (lead.Estimated_Deal_Value_c__c > 50000) {
                score += 20;
            }

            if (lead.Title != null &&
                (lead.Title.contains('VP') ||
                 lead.Title.contains('Director') ||
                 lead.Title.contains('Chief'))) {
                score += 10;
            }

           lead.Lead_Score__c = score;
        }


        // 2. Get Territory Rules
        Map<String, String> territoryOwners = new Map<String, String>();

        for (Territory_Assignment_Rule__mdt rule : [
    SELECT State_Code_c__c, Assigned_Owner_c__c
    FROM Territory_Assignment_Rule__mdt
]) {
    territoryOwners.put(
        rule.State_Code_c__c,
        rule.Assigned_Owner_c__c
    );
}


        // 3. Find Salesforce Users
        Map<String, Id> userIds = new Map<String, Id>();

        for (User user : [
            SELECT Id, Name
            FROM User
            WHERE Name IN :territoryOwners.values()
        ]) {
            userIds.put(user.Name, user.Id);
        }


        // 4. Assign Lead Owner
        for (Lead lead : newLeads) {

            if (territoryOwners.containsKey(lead.State)) {

                String ownerName = territoryOwners.get(lead.State);

                if (userIds.containsKey(ownerName)) {
                    lead.OwnerId = userIds.get(ownerName);
                }
            }
        }
    }
}